### ISSUE TITLE
Verify that requirements.txt is included in environment.yml file

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/make-env#9]
If a `requirements.txt` file is provided, the conda `environment.yml` file should have the following lines;
```yaml
dependencies:
  - pip:
    - -r file:requirements.txt
```

The tooling should check that this correct.
